### ISSUE TITLE
Invalid token for APNS

### ISSUE THREAD

**Issue by Jakanapes** [calonso/ruby-push-notifications#7]
I'm trying to convert from apn_on_rails to this gem and I'm not having any luck with the apn portion.

I keep getting error 8, using the same token and certificate file that I'm using with the other gem.

Is there any specific formatting that needs to be done to the token for this gem?

**Comment by calonso** [comment]
Hi @Jakanapes, 

Tokens should be a string like this '16400b2a275eacf035d22d285d0ffb58fde5b647e54c7da882703136ba4ecd7d6'
Also, error 8 happens when you use a sandbox token with production server or viceversa. Make sure you configure the `sandbox` parameter when initialising the `APNSPusher` object with the proper value.

Hope this helps.

**Comment by calonso** [comment]
Hi @Jakanapes, how are you doing with this?

Could you make it work?

**Comment by Jakanapes** [comment]
Yes, I scrubbed out the spaces and it worked perfectly, thanks!
