### ISSUE TITLE
I got  "Error message individual_results => 255" for ios push notification

### ISSUE THREAD

**Issue by Ipreaw** [calonso/ruby-push-notifications#9]
Everything is ok for me when I tested in local and staging.

Until today I just pushed it to PROD I got error message about individual_results => 255 when I sent one device token. and I got below error when I sent more than one device tokens 

```
NoMethodError: undefined method `unpack' for nil:NilClass

from /app/vendor/bundle/ruby/2.2.0/gems/ruby-push-notifications-0.3.1/lib/ruby-push-notifications/apns/apns_pusher.rb:59:in `push' from (irb):14

from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'

from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'

from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'

from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'

from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'

from /app/bin/rails:8:in `require'

from /app/bin/rails:8:in `<main>'
```

I tested about pem file and device token they're correct. 

Please help me Thank you so much.

**Comment by calonso** [comment]
Hi @Ipreaw 

It looks to me that the error happens because the connection to Apple's APNS is not properly set.

Check that your pem file and token are production ready and also make sure you configure the pusher for production mode (Set the sandbox mode to `false` when creating your pusher `RubyPushNotifications::APNS::APNSPusher.new('the certificate', false)`)

Having a quick look at the code, the `255 UNKNOWN ERROR` code is assigned when the connection to APNS wasn't successful. [https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/apns/apns_pusher.rb#L56-L58](https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/apns/apns_pusher.rb#L56-L58)

Hope this helps.

**Comment by Ipreaw** [comment]
That all is my mistake I forgot to change a sandbox mode to false when push to PROD

I'll closed this issue. Thank you for your help .

**Comment by calonso** [comment]
@Ipreaw Glad to hear that it's working now.
Do you think it would be good to open a Troubleshooting section with experiences like this one?
Would you like to contribute with it?
Cheers!

**Comment by Ipreaw** [comment]
Yes, That's great.  But I never do that before.

**Comment by calonso** [comment]
That's easy, just fork the project and add the `Troubleshooting` section to the README.md file. Then create a pull request and I'll review it before merging.
More info here: [https://help.github.com/articles/using-pull-requests/](https://help.github.com/articles/using-pull-requests/)

**Comment by NikhilSharma972** [comment]
Hi i am facing the same issue, have checked the sandbox mode too. Stuck on it for a time.
